# Generated by Django 5.1.5 on 2026-10-04 05:55

import apps.flota.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número pintado en el vehículo, p. ej. "TC-1024".', max_length=12, unique=True, verbose_name='número interno')),
                ('placa', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}\\d{3}$', 'Formato de placa: ABC123.')])),
                ('tipologia', models.CharField(choices=[('articulado', 'Articulado'), ('padron', 'Padrón'), ('buseton', 'Busetón')], default='padron', max_length=12, verbose_name='tipología')),
                ('capacidad', models.PositiveSmallIntegerField(default=80, help_text='Pasajeros sentados más de pie.', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(250)])),
                ('operador', models.CharField(blank=True, help_text='Empresa concesionaria que opera el vehículo.', max_length=60)),
                ('modelo', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='año modelo')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_servicio', 'En servicio'), ('mantenimiento', 'En mantenimiento'), ('fuera_servicio', 'Fuera de servicio')], default='disponible', max_length=15)),
                ('token_gps', models.CharField(default=apps.flota.models.generar_token_gps, editable=False, help_text='Credencial con la que el equipo a bordo reporta su posición.', max_length=40, unique=True, verbose_name='token del dispositivo GPS')),
            ],
            options={
                'verbose_name': 'bus',
                'verbose_name_plural': 'buses',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='nombre completo')),
                ('documento', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{6,12}$', 'Solo números, entre 6 y 12 dígitos.')], verbose_name='cédula')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='teléfono')),
                ('licencia', models.CharField(max_length=20, unique=True, verbose_name='número de licencia')),
                ('categoria', models.CharField(choices=[('C2', 'C2 · Servicio público (bus/busetón)'), ('C3', 'C3 · Servicio público (articulado)')], default='C2', max_length=2, verbose_name='categoría')),
                ('vencimiento_licencia', models.DateField(verbose_name='vencimiento de la licencia')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('descanso', 'En descanso'), ('incapacitado', 'Incapacitado'), ('inactivo', 'Inactivo')], default='activo', max_length=15)),
            ],
            options={
                'verbose_name': 'conductor',
                'verbose_name_plural': 'conductores',
                'ordering': ['nombre'],
            },
        ),
    ]
