# Generated by Django 5.1.5 on 2026-10-04 05:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(help_text='Identificador corto, p. ej. "bazurto". Se usa en las URL públicas.', max_length=20, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=80)),
                ('tipo', models.CharField(choices=[('portal', 'Portal'), ('estacion', 'Estación troncal'), ('parada', 'Parada de alimentación')], default='estacion', max_length=10)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'estación',
                'verbose_name_plural': 'estaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código visible para el pasajero, p. ej. "T101".', max_length=10, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('troncal', 'Troncal'), ('expresa', 'Expresa'), ('pretroncal', 'Pretroncal'), ('alimentadora', 'Alimentadora')], default='troncal', max_length=15)),
                ('color', models.CharField(default='#1D4ED8', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Usa un color hexadecimal, p. ej. #1D4ED8.')])),
                ('frecuencia_min', models.PositiveSmallIntegerField(default=10, help_text='Cada cuántos minutos debería salir un bus en hora valle.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='frecuencia objetivo (min)')),
                ('velocidad_kmh', models.PositiveSmallIntegerField(default=20, help_text='Promedio incluyendo detenciones. Se usa para estimar tiempos de llegada.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(80)], verbose_name='velocidad comercial (km/h)')),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ParadaRuta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('distancia_km', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='distancia desde el origen (km)')),
                ('minutos_desde_inicio', models.PositiveSmallIntegerField(default=0)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paradas', to='red.estacion')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='red.ruta')),
            ],
            options={
                'verbose_name': 'parada de ruta',
                'verbose_name_plural': 'paradas de ruta',
                'ordering': ['ruta', 'orden'],
                'constraints': [models.UniqueConstraint(fields=('ruta', 'orden'), name='parada_orden_unico_por_ruta')],
            },
        ),
    ]
