# Generated by Django 5.1.5 on 2026-10-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='horario',
            field=models.CharField(blank=True, help_text='Horario de operación que ve el pasajero.', max_length=160),
        ),
        migrations.AddField(
            model_name='ruta',
            name='trazado',
            field=models.JSONField(blank=True, default=list, help_text='Recorrido por la vía como lista [[lat, lng], ...]. Vacío = línea recta entre paradas.'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='tipo',
            field=models.CharField(choices=[('troncal', 'Troncal'), ('expresa', 'Expresa'), ('pretroncal', 'Pretroncal'), ('alimentadora', 'Alimentadora'), ('complementaria', 'Complementaria')], default='troncal', max_length=15),
        ),
    ]
