"""
Configuracion de Django para el sistema de despacho SITM Cartagena.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

load_dotenv(os.path.join(BASE_DIR, '.env'))


def _env_bool(name, default=False):
    return os.getenv(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


# SECURITY WARNING: keep the secret key used in production secret!
# La clave anterior estaba escrita aqui y quedo expuesta en el historial de git,
# por lo que ya no debe reutilizarse. Genera una nueva con:
#   python -c "from django.core.management.utils import get_random_secret_key as k; print(k())"
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
#
# Vercel define la variable VERCEL en sus entornos, asi que alli el valor por
# defecto es False: si se olvida configurar DEBUG, la app no queda mostrando
# trazas de error completas a cualquiera. En local sigue siendo True.
DEBUG = _env_bool('DEBUG', not os.getenv('VERCEL'))

if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-solo-para-desarrollo-local-no-usar-en-produccion'
    else:
        raise RuntimeError(
            'SECRET_KEY no esta definida. Configurala como variable de entorno '
            'antes de correr con DEBUG=False.'
        )

# Hosts permitidos: lista separada por comas. En Vercel se resuelve solo.
ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h.strip()]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']

CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()
]

# En Vercel se confia en los dominios *.vercel.app aunque VERCEL_URL no este
# expuesta. Sin esto, ALLOWED_HOSTS podria quedar vacio y con DEBUG=False
# Django rechazaria todas las peticiones con un 400.
if os.getenv('VERCEL'):
    ALLOWED_HOSTS.append('.vercel.app')
    CSRF_TRUSTED_ORIGINS.append('https://*.vercel.app')

    _vercel_host = os.getenv('VERCEL_URL')
    if _vercel_host:
        ALLOWED_HOSTS.append(_vercel_host)
        CSRF_TRUSTED_ORIGINS.append(f'https://{_vercel_host}')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.core',
    'apps.red',
    'apps.flota',
    'apps.despacho',
    'apps.publico',
    # Tablas del prototipo anterior; solo se conservan sus datos.
    'myapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.core.middleware.CabecerasSeguridad',

]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.core.context_processors.sitm',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# Si DATABASE_URL existe (p. ej. la cadena de Neon) se usa Postgres;
# si no, cae a SQLite local para desarrollo.

DATABASE_URL = os.getenv('DATABASE_URL')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# WhiteNoise sirve los estaticos localizandolos con los finders de Django, sin
# depender de haber corrido collectstatic.
#
# Hace falta porque en una funcion serverless de Vercel no hay un paso de build
# donde ejecutarlo, y el almacenamiento con manifiesto
# (CompressedManifestStaticFilesStorage) exige un staticfiles.json que no
# existiria: cualquier {% static %} reventaria, incluido todo /admin/.
#
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = False

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

# Django 3.2+ exige declarar el tipo de clave primaria por defecto.
# Se deja en AutoField para no forzar una migracion sobre las tablas existentes.
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Ruta del panel de administracion. Cambiarla (p. ej. ADMIN_URL=gestion-7f3k/)
# evita los barridos automaticos contra /admin/. Debe terminar en "/".
ADMIN_URL = os.getenv('ADMIN_URL', 'admin/').strip('/') + '/'

# En Vercel la IP real del cliente llega en X-Forwarded-For (la pone su proxy).
# Fuera de un proxy de confianza esa cabecera es falsificable: no se usa.
CONFIAR_X_FORWARDED_FOR = bool(os.getenv('VERCEL'))

# Autenticacion: el sistema es interno, las cuentas las crea un administrador.
LOGIN_URL = 'cuentas:ingresar'
LOGIN_REDIRECT_URL = 'operacion:tablero'
LOGOUT_REDIRECT_URL = 'cuentas:ingresar'

# Modo demostracion: despacha y cierra recorridos automaticamente para que el
# mapa en vivo siempre tenga buses. Nunca activarlo en una operacion real.
SITM_MODO_DEMO = _env_bool('SITM_MODO_DEMO', False)

# Token PUBLICO de Mapbox (empieza por "pk."). Se envia al navegador, asi que
# en el panel de Mapbox restringelo a los dominios de la app. Si esta vacio,
# los mapas usan las teselas libres de OpenStreetMap.
MAPBOX_TOKEN = os.getenv('MAPBOX_TOKEN', '').strip()

# Cada cuantos segundos las pantallas en vivo piden posiciones nuevas.
SITM_REFRESCO_S = int(os.getenv('SITM_REFRESCO_S', '10'))

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'loggers': {'apps': {'handlers': ['console'], 'level': 'INFO'}},
}

# Seguridad en produccion (solo cuando DEBUG=False)
if not DEBUG:
    # Vercel termina el TLS y reenvia el protocolo original en esta cabecera.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000  # 1 anio
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
    SESSION_COOKIE_HTTPONLY = True
    # La sesion expira tras 12 horas (un turno de operacion).
    SESSION_COOKIE_AGE = 12 * 60 * 60

