# Generated by Django 5.1.5 on 2026-08-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('licencia', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='nos',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('R', 'Despachado'), ('C', 'Cancelado')], default='R', max_length=2),
        ),
        migrations.AlterField(
            model_name='bus',
            name='nos',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bus',
            name='price',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bus',
            name='rem',
            field=models.CharField(max_length=30),
        ),
    ]
