# Generated by Django 5.1.5 on 2026-08-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_crear_drivers_y_ajustar_campos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'despacho', 'verbose_name_plural': 'despachos'},
        ),
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name': 'bus', 'verbose_name_plural': 'buses'},
        ),
        migrations.AlterModelOptions(
            name='drivers',
            options={'verbose_name': 'conductor', 'verbose_name_plural': 'conductores'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'usuario (modelo heredado)', 'verbose_name_plural': 'usuarios (modelo heredado)'},
        ),
    ]
