# Generated by Django 5.1.5 on 2026-10-04 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flota', '0001_initial'),
        ('red', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_ruta', 'En ruta'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='programado', max_length=12)),
                ('hora_programada', models.DateTimeField()),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('hora_llegada', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='flota.bus')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='flota.conductor')),
                ('despachador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachos', to=settings.AUTH_USER_MODEL)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='red.ruta')),
            ],
            options={
                'ordering': ['-hora_programada'],
            },
        ),
        migrations.CreateModel(
            name='EventoDespacho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('creado', 'Despacho creado'), ('salida', 'Salida a ruta'), ('llegada', 'Llegada a destino'), ('incidente', 'Incidente'), ('cancelacion', 'Cancelación'), ('nota', 'Nota')], max_length=12)),
                ('descripcion', models.CharField(blank=True, max_length=280, verbose_name='descripción')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='despacho.despacho')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento de despacho',
                'verbose_name_plural': 'eventos de despacho',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='PosicionGPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('velocidad_kmh', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('registrado', models.DateTimeField(db_index=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='flota.bus')),
                ('despacho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posiciones', to='despacho.despacho')),
            ],
            options={
                'verbose_name': 'posición GPS',
                'verbose_name_plural': 'posiciones GPS',
                'ordering': ['-registrado'],
            },
        ),
        migrations.AddIndex(
            model_name='despacho',
            index=models.Index(fields=['estado', 'hora_programada'], name='despacho_de_estado_01498d_idx'),
        ),
        migrations.AddIndex(
            model_name='despacho',
            index=models.Index(fields=['ruta', 'hora_salida'], name='despacho_de_ruta_id_865582_idx'),
        ),
        migrations.AddConstraint(
            model_name='despacho',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['programado', 'en_ruta'])), fields=('bus',), name='un_despacho_activo_por_bus'),
        ),
        migrations.AddConstraint(
            model_name='despacho',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['programado', 'en_ruta'])), fields=('conductor',), name='un_despacho_activo_por_conductor'),
        ),
        migrations.AddIndex(
            model_name='posiciongps',
            index=models.Index(fields=['despacho', '-registrado'], name='despacho_po_despach_158f58_idx'),
        ),
    ]
